In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

#  Merging the data

In [5]:
movies = movies.merge(credits,on = 'title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

# Removing the unwanted column

In [7]:
movies = movies[['movie_id', 'title','overview','genres','keywords','cast','crew']]

In [8]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.duplicated().sum()

0

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [15]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies['genres'] = movies['genres'].apply(convert)

In [17]:
movies['keywords'] = movies['keywords'].apply(convert)

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
             L.append(i['name'])
             counter+=1
        else:
            break
    return L

In [20]:
movies['cast'] = movies['cast'].apply(convert3)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [23]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [25]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

# Removing Space Between Word

In [27]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

# Creating a new column

In [29]:
movies['tags'] = movies['overview'] + movies['keywords'] + movies['cast'] + movies['crew']

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

# Creating new dataframe

In [31]:
new_df = movies[['movie_id', 'title', 'tags']]

In [32]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [33]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\shail\AppData\Local\Temp\ipykernel_14420\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [34]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [35]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

# Convert into lower case

In [36]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\shail\AppData\Local\Temp\ipykernel_14420\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [37]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

# Vectorization for recommadation ML projects

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [39]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [40]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [41]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\shail\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\shail\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\shail\anaconda3\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\shail\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\shail\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\shail\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [43]:
import nltk

In [44]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [45]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return  " ".join(y)

In [46]:
new_df['tags']= new_df['tags'].apply(stem)

C:\Users\shail\AppData\Local\Temp\ipykernel_14420\3021978705.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(stem)

In [47]:
# Example
ps.stem('loved')

'love'

# Cosine Similarities

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
cosine_similarity(vectors).shape

(4806, 4806)

In [50]:
similarity = cosine_similarity(vectors)

In [51]:
similarity

array([[1.        , 0.        , 0.        , ..., 0.        , 0.02752409,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02865341, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.02865341, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02865341, 0.02865341, ..., 1.        , 0.048795  ,
        0.05006262],
       [0.02752409, 0.        , 0.        , ..., 0.048795  , 1.        ,
        0.05129892],
       [0.        , 0.        , 0.        , ..., 0.05006262, 0.05129892,
        1.        ]])

In [52]:
similarity[2]

array([0.        , 0.        , 1.        , ..., 0.02865341, 0.        ,
       0.        ])

In [53]:
# Fixing the index

list(enumerate(similarity[0]))

[(0, 1.0000000000000004),
 (1, 0.0),
 (2, 0.0),
 (3, 0.021110016546037454),
 (4, 0.11295649894498103),
 (5, 0.05025189076296061),
 (6, 0.0),
 (7, 0.05647824947249051),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (11, 0.029424494316824985),
 (12, 0.0),
 (13, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.06917144638660747),
 (18, 0.07173421497882157),
 (19, 0.022662980454966834),
 (20, 0.0),
 (21, 0.033501260508640406),
 (22, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.03798685881987932),
 (26, 0.09231861823449955),
 (27, 0.12562972690740154),
 (28, 0.03481553119113957),
 (29, 0.025125945381480306),
 (30, 0.0),
 (31, 0.07106690545187017),
 (32, 0.02461829819586655),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.11769797726729994),
 (37, 0.030303030303030307),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0787295821622217),
 (42, 0.0),
 (43, 0.051899929610768204),
 (44, 0.0),
 (45, 0.0492365963917331),
 (46, 0.0646508183835236),
 (47, 0.16000261230887305),
 (48, 0.023911404992940522),
 (49, 0.03413943709994595),
 (50, 0.0),
 (51, 0.022662980454966834),
 (52, 0.06253053994807226),
 (53, 0.0),
 (54, 0.0),
 (55, 0.021110016546037454),
 (56, 0.03993615319154359),
 (57, 0.030772872744833184),
 (58, 0.0),
 (59, 0.021110016546037454),
 (60, 0.030772872744833184),
 (61, 0.08444006618414981),
 (62, 0.0),
 (63, 0.04494665749754947),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0969762275752854),
 (68, 0.037113480951260276),
 (69, 0.018349396085439344),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.0),
 (74, 0.18582615562066462),
 (75, 0.0323254091917618),
 (76, 0.0),
 (77, 0.015760250451281974),
 (78, 0.0),
 (79, 0.0),
 (80, 0.0),
 (81, 0.041612518928823956),
 (82, 0.030303030303030307),
 (83, 0.11149893466761211),
 (84, 0.04571503208824944),
 (85, 0.05567022142689042),
 (86, 0.033501260508640406),
 (87, 0.0646508183835236),
 (88, 0.03481553119113957),
 (89, 0.0484881137876427),
 (90, 0.0),
 (91, 0.0682788741998919),
 (92, 0.025125945381480306),
 (93, 0.0),
 (94, 0.07259540086406278),
 (95, 0.08058229640253804),
 (96, 0.0),
 (97, 0.0),
 (98, 0.0),
 (99, 0.0),
 (100, 0.0),
 (101, 0.0),
 (102, 0.04737793696791343),
 (103, 0.023911404992940522),
 (104, 0.0),
 (105, 0.03798685881987932),
 (106, 0.0),
 (107, 0.024140227479263383),
 (108, 0.1037998592215364),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0657951694959769),
 (112, 0.0),
 (113, 0.0),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.0),
 (118, 0.0),
 (119, 0.02686076546751268),
 (120, 0.0),
 (121, 0.0),
 (122, 0.0),
 (123, 0.053093187320189895),
 (124, 0.02566635011696727),
 (125, 0.03365744438798206),
 (126, 0.03126526997403613),
 (127, 0.04222003309207491),
 (128, 0.0),
 (129, 0.028239124736245257),
 (130, 0.0),
 (131, 0.030772872744833184),
 (132, 0.023688968483956716),
 (133, 0.0),
 (134, 0.07422696190252055),
 (135, 0.0),
 (136, 0.0),
 (137, 0.035909478570327065),
 (138, 0.0),
 (139, 0.04611429759107165),
 (140, 0.027186362391351845),
 (141, 0.08444006618414981),
 (142, 0.03553345272593508),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.018148850216015696),
 (147, 0.0),
 (148, 0.03892494720807615),
 (149, 0.11528574397767913),
 (150, 0.13373015960759796),
 (151, 0.13957263155977065),
 (152, 0.0),
 (153, 0.04571503208824944),
 (154, 0.0),
 (155, 0.0),
 (156, 0.048280454958526765),
 (157, 0.03798685881987932),
 (158, 0.055749467333806056),
 (159, 0.0),
 (160, 0.041612518928823956),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (164, 0.0),
 (165, 0.0),
 (166, 0.03289758474798845),
 (167, 0.0),
 (168, 0.05970814340265321),
 (169, 0.050783671611902566),
 (170, 0.04875149494180871),
 (171, 0.0),
 (172, 0.04652421051992355),
 (173, 0.026243194054073903),
 (174, 0.029854071701326604),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.04494665749754947),
 (180, 0.0),
 (181, 0.0),
 (182, 0.028618190351607124),
 (183, 0.01958526645373187),
 (184, 0.1411956236812263),
 (185, 0.0),
 (186, 0.0),
 (187, 0.0),
 (188, 0.0),
 (189, 0.04494665749754947),
 (190, 0.02285751604412472),
 (191, 0.0),
 (192, 0.0),
 (193, 0.023262105259961776),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.0),
 (199, 0.04875149494180871),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (205, 0.0),
 (206, 0.04074849710853642),
 (207, 0.0),
 (208, 0.048280454958526765),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (212, 0.0),
 (213, 0.023057148795535824),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.0),
 (219, 0.0),
 (220, 0.13400504203456162),
 (221, 0.0),
 (222, 0.048280454958526765),
 (223, 0.029424494316824985),
 (224, 0.022107884414269096),
 (225, 0.0),
 (226, 0.0),
 (227, 0.03289758474798845),
 (228, 0.055048188256318034),
 (229, 0.02095648711539772),
 (230, 0.023911404992940522),
 (231, 0.0),
 (232, 0.0),
 (233, 0.0),
 (234, 0.0),
 (235, 0.0),
 (236, 0.07597371763975865),
 (237, 0.0),
 (238, 0.04532596090993367),
 (239, 0.09389050536260406),
 (240, 0.0),
 (241, 0.0),
 (242, 0.0),
 (243, 0.027186362391351845),
 (244, 0.03413943709994595),
 (245, 0.03289758474798845),
 (246, 0.047822809985881044),
 (247, 0.0),
 (248, 0.0),
 (249, 0.07987230638308718),
 (250, 0.0),
 (251, 0.04494665749754947),
 (252, 0.0),
 (253, 0.023911404992940522),
 (254, 0.03178208630818641),
 (255, 0.0),
 (256, 0.0),
 (257, 0.03126526997403613),
 (258, 0.0),
 (259, 0.0),
 (260, 0.14213381090374033),
 (261, 0.0),
 (262, 0.0),
 (263, 0.0),
 (264, 0.0),
 (265, 0.0),
 (266, 0.05884898863364997),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (270, 0.055048188256318034),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.05048616658197308),
 (275, 0.0682788741998919),
 (276, 0.0),
 (277, 0.023262105259961776),
 (278, 0.027874733666903028),
 (279, 0.08155908717405554),
 (280, 0.0),
 (281, 0.0787295821622217),
 (282, 0.03178208630818641),
 (283, 0.0),
 (284, 0.0),
 (285, 0.0),
 (286, 0.0),
 (287, 0.029012942659282975),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.03413943709994595),
 (295, 0.06253053994807226),
 (296, 0.0),
 (297, 0.025949964805384102),
 (298, 0.0),
 (299, 0.0),
 (300, 0.1144727614064285),
 (301, 0.1488687935206897),
 (302, 0.0),
 (303, 0.0),
 (304, 0.03754255278891389),
 (305, 0.14083575804390608),
 (306, 0.03413943709994595),
 (307, 0.07299318686018119),
 (308, 0.03892494720807615),
 (309, 0.0),
 (310, 0.0),
 (311, 0.11149893466761211),
 (312, 0.06253053994807226),
 (313, 0.08444006618414981),
 (314, 0.0),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (320, 0.0),
 (321, 0.0),
 (322, 0.1250610798961445),
 (323, 0.0),
 (324, 0.0),
 (325, 0.04652421051992355),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.0),
 (330, 0.029424494316824985),
 (331, 0.0),
 (332, 0.06253053994807226),
 (333, 0.0),
 (334, 0.029012942659282975),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.08263686767584087),
 (343, 0.023911404992940522),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.03798685881987932),
 (349, 0.0),
 (350, 0.0),
 (351, 0.0),
 (352, 0.0),
 (353, 0.0),
 (354, 0.0),
 (355, 0.0),
 (356, 0.03413943709994595),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.0),
 (361, 0.029854071701326604),
 (362, 0.03553345272593508),
 (363, 0.04875149494180871),
 (364, 0.0),
 (365, 0.05723638070321425),
 (366, 0.0),
 (367, 0.0),
 (368, 0.07422696190252055),
 (369, 0.06253053994807226),
 (370, 0.0),
 (371, 0.0),
 (372, 0.028618190351607124),
 (373, 0.1519474352795173),
 (374, 0.0),
 (375, 0.022473328748774734),
 (376, 0.0),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0),
 (385, 0.0),
 (386, 0.0),
 (387, 0.0),
 (388, 0.0),
 (389, 0.037113480951260276),
 (390, 0.0),
 (391, 0.022107884414269096),
 (392, 0.0),
 (393, 0.0),
 (394, 0.0),
 (395, 0.03126526997403613),
 (396, 0.0),
 (397, 0.030303030303030307),
 (398, 0.0),
 (399, 0.0),
 (400, 0.0),
 (401, 0.03629770043203139),
 (402, 0.0),
 (403, 0.0),
 (404, 0.037113480951260276),
 (405, 0.0),
 (406, 0.023262105259961776),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.028239124736245257),
 (411, 0.0),
 (412, 0.027524094128159017),
 (413, 0.03178208630818641),
 (414, 0.0),
 (415, 0.037113480951260276),
 (416, 0.0),
 (417, 0.0),
 (418, 0.04103049699311092),
 (419, 0.0),
 (420, 0.028239124736245257),
 (421, 0.0),
 (422, 0.0778498944161523),
 (423, 0.027186362391351845),
 (424, 0.0),
 (425, 0.025125945381480306),
 (426, 0.0),
 (427, 0.0),
 (428, 0.020659216918960218),
 (429, 0.0),
 (430, 0.05723638070321425),
 (431, 0.0),
 (432, 0.08058229640253804),
 (433, 0.0),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (439, 0.033501260508640406),
 (440, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.0),
 (444, 0.0),
 (445, 0.0),
 (446, 0.0),
 (447, 0.0),
 (448, 0.027186362391351845),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.10497277621629561),
 (455, 0.0),
 (456, 0.051899929610768204),
 (457, 0.0),
 (458, 0.025391835805951283),
 (459, 0.0),
 (460, 0.0),
 (461, 0.1305582419667734),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.11677484162422844),
 (467, 0.024375747470904353),
 (468, 0.0),
 (469, 0.02486823656509969),
 (470, 0.0),
 (471, 0.0),
 (472, 0.0),
 (473, 0.05647824947249051),
 (474, 0.0),
 (475, 0.024140227479263383),
 (476, 0.03993615319154359),
 (477, 0.0),
 (478, 0.0),
 (479, 0.08040302522073696),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (483, 0.03553345272593508),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0),
 (487, 0.0778498944161523),
 (488, 0.041612518928823956),
 (489, 0.0),
 (490, 0.04351941398892446),
 (491, 0.023688968483956716),
 (492, 0.03481553119113957),
 (493, 0.0),
 (494, 0.0),
 (495, 0.11980845957463077),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.0),
 (501, 0.023688968483956716),
 (502, 0.13593181195675924),
 (503, 0.0),
 (504, 0.0),
 (505, 0.04103049699311092),
 (506, 0.03993615319154359),
 (507, 0.19500597976723483),
 (508, 0.0),
 (509, 0.0),
 (510, 0.05723638070321425),
 (511, 0.0),
 (512, 0.03289758474798845),
 (513, 0.06356417261637282),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.030772872744833184),
 (522, 0.0),
 (523, 0.0),
 (524, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (529, 0.11149893466761211),
 (530, 0.03993615319154359),
 (531, 0.0),
 (532, 0.024140227479263383),
 (533, 0.03993615319154359),
 (534, 0.0),
 (535, 0.030772872744833184),
 (536, 0.05647824947249051),
 (537, 0.0),
 (538, 0.0),
 (539, 0.20100756305184245),
 (540, 0.0),
 (541, 0.02461829819586655),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (546, 0.037113480951260276),
 (547, 0.0),
 (548, 0.0),
 (549, 0.10379985922153641),
 (550, 0.030303030303030307),
 (551, 0.0),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (555, 0.017584498711333246),
 (556, 0.0),
 (557, 0.1250610798961445),
 (558, 0.0),
 (559, 0.0),
 (560, 0.023911404992940522),
 (561, 0.0),
 (562, 0.0),
 (563, 0.0),
 (564, 0.07597371763975865),
 (565, 0.0),
 (566, 0.0),
 (567, 0.0),
 (568, 0.09379580992210837),
 (569, 0.0),
 (570, 0.04103049699311092),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.06700252101728081),
 (578, 0.027186362391351845),
 (579, 0.10444659357341872),
 (580, 0.0),
 (581, 0.07259540086406278),
 (582, 0.20533080093573816),
 (583, 0.0),
 (584, 0.0),
 (585, 0.0),
 (586, 0.0),
 (587, 0.028618190351607124),
 (588, 0.030772872744833184),
 (589, 0.05372153093502536),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (595, 0.08703882797784893),
 (596, 0.026243194054073903),
 (597, 0.0),
 (598, 0.0),
 (599, 0.035719981318454656),
 (600, 0.02566635011696727),
 (601, 0.0),
 (602, 0.0),
 (603, 0.0),
 (604, 0.0),
 (605, 0.0),
 (606, 0.0),
 (607, 0.0),
 (608, 0.0),
 (609, 0.0),
 (610, 0.0),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0),
 (614, 0.06356417261637282),
 (615, 0.0),
 (616, 0.0),
 (617, 0.03178208630818641),
 (618, 0.0),
 (619, 0.0),
 (620, 0.0),
 (621, 0.03993615319154359),
 (622, 0.0),
 (623, 0.0),
 (624, 0.04652421051992355),
 (625, 0.0),
 (626, 0.0657951694959769),
 (627, 0.0),
 (628, 0.0),
 (629, 0.02686076546751268),
 (630, 0.0),
 (631, 0.0),
 (632, 0.060606060606060615),
 (633, 0.0),
 (634, 0.030772872744833184),
 (635, 0.07784989441615231),
 (636, 0.0),
 (637, 0.028239124736245257),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (641, 0.0),
 (642, 0.0),
 (643, 0.05723638070321425),
 (644, 0.0),
 (645, 0.0),
 (646, 0.030772872744833184),
 (647, 0.055749467333806056),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.04652421051992355),
 (654, 0.0),
 (655, 0.0),
 (656, 0.0),
 (657, 0.0),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.09143006417649888),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (666, 0.027524094128159017),
 (667, 0.0),
 (668, 0.0),
 (669, 0.03892494720807615),
 (670, 0.0),
 (671, 0.028618190351607124),
 (672, 0.030772872744833184),
 (673, 0.0),
 (674, 0.027874733666903028),
 (675, 0.0),
 (676, 0.0),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0657951694959769),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (684, 0.0),
 (685, 0.0),
 (686, 0.0),
 (687, 0.0646508183835236),
 (688, 0.02686076546751268),
 (689, 0.0),
 (690, 0.0),
 (691, 0.0),
 (692, 0.12833175058483634),
 (693, 0.0),
 (694, 0.0),
 (695, 0.0),
 (696, 0.0),
 (697, 0.0),
 (698, 0.0),
 (699, 0.0),
 (700, 0.0),
 (701, 0.06963106238227915),
 (702, 0.0),
 (703, 0.0),
 (704, 0.053093187320189895),
 (705, 0.0),
 (706, 0.0),
 (707, 0.0),
 (708, 0.0),
 (709, 0.0),
 (710, 0.0),
 (711, 0.0),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (715, 0.0),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (719, 0.0),
 (720, 0.0),
 (721, 0.0),
 (722, 0.0),
 (723, 0.0),
 (724, 0.0),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.0),
 (729, 0.0),
 (730, 0.0),
 (731, 0.0),
 (732, 0.0),
 (733, 0.023911404992940522),
 (734, 0.0),
 (735, 0.0),
 (736, 0.0),
 (737, 0.05723638070321425),
 (738, 0.0),
 (739, 0.0),
 (740, 0.08471737420873576),
 (741, 0.0),
 (742, 0.0),
 (743, 0.0),
 (744, 0.0),
 (745, 0.0),
 (746, 0.0),
 (747, 0.0),
 (748, 0.0),
 (749, 0.0),
 (750, 0.02686076546751268),
 (751, 0.0),
 (752, 0.06154574548966637),
 (753, 0.0),
 (754, 0.05970814340265321),
 (755, 0.0),
 (756, 0.0),
 (757, 0.0),
 (758, 0.027874733666903028),
 (759, 0.0),
 (760, 0.0),
 (761, 0.0),
 (762, 0.0),
 (763, 0.0),
 (764, 0.0),
 (765, 0.0),
 (766, 0.0),
 (767, 0.0),
 (768, 0.0),
 (769, 0.0),
 (770, 0.02686076546751268),
 (771, 0.0),
 (772, 0.0),
 (773, 0.0),
 (774, 0.0),
 (775, 0.06700252101728081),
 (776, 0.0),
 (777, 0.025125945381480306),
 (778, 0.08471737420873576),
 (779, 0.0),
 (780, 0.0),
 (781, 0.0),
 (782, 0.027874733666903028),
 (783, 0.0),
 (784, 0.0),
 (785, 0.06632365324280728),
 (786, 0.0),
 (787, 0.0657951694959769),
 (788, 0.0),
 (789, 0.0),
 (790, 0.050783671611902566),
 (791, 0.03892494720807615),
 (792, 0.0),
 (793, 0.0),
 (794, 0.03413943709994595),
 (795, 0.0),
 (796, 0.0),
 (797, 0.0),
 (798, 0.0),
 (799, 0.039675980042907705),
 (800, 0.0),
 (801, 0.0),
 (802, 0.0),
 (803, 0.026546593660094948),
 (804, 0.028618190351607124),
 (805, 0.0),
 (806, 0.026243194054073903),
 (807, 0.030772872744833184),
 (808, 0.048280454958526765),
 (809, 0.0),
 (810, 0.0),
 (811, 0.0),
 (812, 0.050783671611902566),
 (813, 0.0),
 (814, 0.0),
 (815, 0.0),
 (816, 0.0),
 (817, 0.0),
 (818, 0.0),
 (819, 0.0),
 (820, 0.0),
 (821, 0.0),
 (822, 0.0),
 (823, 0.03413943709994595),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0),
 (827, 0.027524094128159017),
 (828, 0.0),
 (829, 0.0),
 (830, 0.0),
 (831, 0.0),
 (832, 0.0),
 (833, 0.0),
 (834, 0.0),
 (835, 0.028618190351607124),
 (836, 0.0),
 (837, 0.0323254091917618),
 (838, 0.13373015960759796),
 (839, 0.0),
 (840, 0.0),
 (841, 0.0),
 (842, 0.0),
 (843, 0.0646508183835236),
 (844, 0.03413943709994595),
 (845, 0.0),
 (846, 0.0),
 (847, 0.060606060606060615),
 (848, 0.021266970502955673),
 (849, 0.0),
 (850, 0.0),
 (851, 0.0),
 (852, 0.0),
 (853, 0.0),
 (854, 0.060606060606060615),
 (855, 0.0323254091917618),
 (856, 0.0),
 (857, 0.0),
 (858, 0.0),
 (859, 0.0),
 (860, 0.0),
 (861, 0.04652421051992355),
 (862, 0.0),
 (863, 0.0),
 (864, 0.0),
 (865, 0.0),
 (866, 0.0),
 (867, 0.0),
 (868, 0.0),
 (869, 0.0),
 (870, 0.0),
 (871, 0.03126526997403613),
 (872, 0.0),
 (873, 0.0),
 (874, 0.0),
 (875, 0.030772872744833184),
 (876, 0.0),
 (877, 0.0),
 (878, 0.03798685881987932),
 (879, 0.0),
 (880, 0.0),
 (881, 0.0),
 (882, 0.0),
 (883, 0.03126526997403613),
 (884, 0.0),
 (885, 0.06253053994807226),
 (886, 0.0),
 (887, 0.03942082639927218),
 (888, 0.0),
 (889, 0.058755799361195606),
 (890, 0.0),
 (891, 0.0),
 (892, 0.0),
 (893, 0.0),
 (894, 0.03289758474798845),
 (895, 0.0),
 (896, 0.0),
 (897, 0.05802588531856595),
 (898, 0.028618190351607124),
 (899, 0.03289758474798845),
 (900, 0.06154574548966637),
 (901, 0.0657951694959769),
 (902, 0.0),
 (903, 0.0),
 (904, 0.0),
 (905, 0.0),
 (906, 0.0),
 (907, 0.0),
 (908, 0.05647824947249051),
 (909, 0.0),
 (910, 0.0),
 (911, 0.0),
 (912, 0.0),
 (913, 0.0),
 (914, 0.0),
 (915, 0.0),
 (916, 0.0),
 (917, 0.0),
 (918, 0.0),
 (919, 0.0),
 (920, 0.0),
 (921, 0.0),
 (922, 0.0),
 (923, 0.0),
 (924, 0.0),
 (925, 0.0),
 (926, 0.0),
 (927, 0.0),
 (928, 0.0),
 (929, 0.0),
 (930, 0.0),
 (931, 0.07259540086406278),
 (932, 0.0),
 (933, 0.028239124736245257),
 (934, 0.0),
 (935, 0.0),
 (936, 0.0),
 (937, 0.03289758474798845),
 (938, 0.0),
 (939, 0.04694525268130203),
 (940, 0.0),
 (941, 0.0),
 (942, 0.11396057645963797),
 (943, 0.0),
 (944, 0.0),
 (945, 0.03629770043203139),
 (946, 0.028618190351607124),
 (947, 0.0),
 (948, 0.0),
 (949, 0.0),
 (950, 0.0),
 (951, 0.03629770043203139),
 (952, 0.0),
 (953, 0.0),
 (954, 0.0),
 (955, 0.0),
 (956, 0.0),
 (957, 0.0),
 (958, 0.0),
 (959, 0.0),
 (960, 0.0),
 (961, 0.0),
 (962, 0.0),
 (963, 0.027186362391351845),
 (964, 0.0),
 (965, 0.0),
 (966, 0.0),
 (967, 0.0),
 (968, 0.0),
 (969, 0.0),
 (970, 0.0),
 (971, 0.0),
 (972, 0.10444659357341872),
 (973, 0.0969762275752854),
 (974, 0.013273296830047474),
 (975, 0.012974982402692051),
 (976, 0.0),
 (977, 0.0),
 (978, 0.0),
 (979, 0.0),
 (980, 0.0),
 (981, 0.0),
 (982, 0.02461829819586655),
 (983, 0.0),
 (984, 0.0),
 (985, 0.0),
 (986, 0.0),
 (987, 0.0),
 (988, 0.060606060606060615),
 (989, 0.0),
 (990, 0.0),
 (991, 0.0),
 (992, 0.0),
 (993, 0.0),
 (994, 0.0),
 (995, 0.0),
 (996, 0.0),
 (997, 0.026243194054073903),
 (998, 0.0),
 (999, 0.0),
 ...]

In [54]:
sorted(list(enumerate(similarity[0])), reverse=True, key= lambda x:x[1]) # sorting based on 2 no.

[(0, 1.0000000000000004),
 (3608, 0.21320071635561044),
 (1216, 0.20769510081357428),
 (1920, 0.2059714602177749),
 (582, 0.20533080093573816),
 (539, 0.20100756305184245),
 (2409, 0.20032733246124987),
 (507, 0.19500597976723483),
 (74, 0.18582615562066462),
 (3538, 0.17654696590094993),
 (3730, 0.17407765595569785),
 (1321, 0.16888013236829963),
 (47, 0.16000261230887305),
 (4192, 0.15974461276617435),
 (2204, 0.15891043154093204),
 (3162, 0.1574591643244434),
 (2333, 0.15569978883230462),
 (1201, 0.1556997888323046),
 (2731, 0.1556997888323046),
 (373, 0.1519474352795173),
 (1329, 0.1519474352795173),
 (1204, 0.149270358506633),
 (301, 0.1488687935206897),
 (1275, 0.14519080172812557),
 (2515, 0.14519080172812557),
 (1071, 0.14506471329641488),
 (260, 0.14213381090374033),
 (2786, 0.14213381090374033),
 (184, 0.1411956236812263),
 (305, 0.14083575804390608),
 (151, 0.13957263155977065),
 (3327, 0.13957263155977065),
 (1537, 0.1392621247645583),
 (2971, 0.13834289277321493),
 (502, 0.13593181195675924),
 (220, 0.13400504203456162),
 (150, 0.13373015960759796),
 (838, 0.13373015960759796),
 (3628, 0.1315903389919538),
 (461, 0.1305582419667734),
 (692, 0.12833175058483634),
 (27, 0.12562972690740154),
 (322, 0.1250610798961445),
 (557, 0.1250610798961445),
 (495, 0.11980845957463077),
 (36, 0.11769797726729994),
 (466, 0.11677484162422844),
 (1965, 0.11631052629980888),
 (1383, 0.1160517706371319),
 (1444, 0.1160517706371319),
 (1479, 0.1160517706371319),
 (4336, 0.1160517706371319),
 (149, 0.11528574397767913),
 (300, 0.1144727614064285),
 (942, 0.11396057645963797),
 (4, 0.11295649894498103),
 (83, 0.11149893466761211),
 (311, 0.11149893466761211),
 (529, 0.11149893466761211),
 (1355, 0.11009637651263607),
 (2547, 0.10744306187005072),
 (454, 0.10497277621629561),
 (579, 0.10444659357341872),
 (972, 0.10444659357341872),
 (1747, 0.10444659357341872),
 (549, 0.10379985922153641),
 (108, 0.1037998592215364),
 (1357, 0.1037998592215364),
 (1322, 0.10156734322380513),
 (3630, 0.09947294626039876),
 (2873, 0.0984731927834662),
 (67, 0.0969762275752854),
 (973, 0.0969762275752854),
 (1715, 0.09656090991705353),
 (1002, 0.09564561997176209),
 (4048, 0.09564561997176209),
 (1344, 0.09534625892455922),
 (239, 0.09389050536260406),
 (568, 0.09379580992210837),
 (1194, 0.0930484210398471),
 (26, 0.09231861823449955),
 (1220, 0.09231861823449955),
 (661, 0.09143006417649888),
 (4545, 0.09143006417649888),
 (1808, 0.09090909090909093),
 (1741, 0.08989331499509894),
 (2551, 0.08989331499509894),
 (3622, 0.08956221510397981),
 (4230, 0.08956221510397981),
 (1015, 0.08827348295047496),
 (595, 0.08703882797784893),
 (1765, 0.08703882797784893),
 (2136, 0.08703882797784893),
 (3409, 0.08703882797784893),
 (3675, 0.08703882797784893),
 (3839, 0.08703882797784893),
 (3147, 0.0863667034175061),
 (1056, 0.08585457105482137),
 (740, 0.08471737420873576),
 (778, 0.08471737420873576),
 (61, 0.08444006618414981),
 (141, 0.08444006618414981),
 (313, 0.08444006618414981),
 (1045, 0.08444006618414981),
 (1348, 0.08444006618414981),
 (1488, 0.08444006618414981),
 (3663, 0.08444006618414981),
 (1831, 0.08362420100070908),
 (2284, 0.08362420100070908),
 (342, 0.08263686767584087),
 (1846, 0.08257228238447706),
 (3443, 0.08257228238447706),
 (2456, 0.08206099398622184),
 (2584, 0.08206099398622184),
 (3954, 0.08206099398622184),
 (279, 0.08155908717405554),
 (95, 0.08058229640253804),
 (432, 0.08058229640253804),
 (479, 0.08040302522073696),
 (249, 0.07987230638308718),
 (41, 0.0787295821622217),
 (281, 0.0787295821622217),
 (1512, 0.0787295821622217),
 (635, 0.07784989441615231),
 (422, 0.0778498944161523),
 (487, 0.0778498944161523),
 (1277, 0.0778498944161523),
 (1774, 0.0778498944161523),
 (2620, 0.0778498944161523),
 (3976, 0.0778498944161523),
 (2488, 0.07617550741785385),
 (236, 0.07597371763975865),
 (564, 0.07597371763975865),
 (1166, 0.07597371763975865),
 (2496, 0.07597371763975865),
 (2622, 0.07597371763975865),
 (2660, 0.07597371763975865),
 (2970, 0.07597371763975865),
 (3376, 0.07597371763975865),
 (1278, 0.07460470969529907),
 (134, 0.07422696190252055),
 (368, 0.07422696190252055),
 (3109, 0.07422696190252055),
 (3736, 0.07422696190252055),
 (1007, 0.07385489458759964),
 (307, 0.07299318686018119),
 (94, 0.07259540086406278),
 (581, 0.07259540086406278),
 (931, 0.07259540086406278),
 (1097, 0.07259540086406278),
 (2652, 0.07259540086406278),
 (2955, 0.07259540086406278),
 (18, 0.07173421497882157),
 (1497, 0.07173421497882157),
 (31, 0.07106690545187017),
 (1274, 0.07106690545187017),
 (1929, 0.07106690545187017),
 (2840, 0.07106690545187017),
 (4793, 0.07106690545187017),
 (2099, 0.07041787902195304),
 (701, 0.06963106238227915),
 (1178, 0.06963106238227915),
 (2093, 0.06963106238227915),
 (3301, 0.06963106238227915),
 (3449, 0.06963106238227915),
 (17, 0.06917144638660747),
 (2203, 0.06917144638660747),
 (91, 0.0682788741998919),
 (275, 0.0682788741998919),
 (1207, 0.0682788741998919),
 (1700, 0.0682788741998919),
 (2247, 0.0682788741998919),
 (3537, 0.0682788741998919),
 (2648, 0.0679889413649005),
 (1926, 0.0674199862463242),
 (577, 0.06700252101728081),
 (775, 0.06700252101728081),
 (2552, 0.06700252101728081),
 (1534, 0.06686507980379898),
 (3431, 0.06686507980379898),
 (785, 0.06632365324280728),
 (111, 0.0657951694959769),
 (626, 0.0657951694959769),
 (680, 0.0657951694959769),
 (787, 0.0657951694959769),
 (901, 0.0657951694959769),
 (1378, 0.0657951694959769),
 (1790, 0.0657951694959769),
 (2232, 0.0657951694959769),
 (3310, 0.0657951694959769),
 (3910, 0.0657951694959769),
 (4097, 0.0657951694959769),
 (1574, 0.06477502756312958),
 (46, 0.0646508183835236),
 (87, 0.0646508183835236),
 (687, 0.0646508183835236),
 (843, 0.0646508183835236),
 (1031, 0.0646508183835236),
 (1161, 0.0646508183835236),
 (1616, 0.0646508183835236),
 (513, 0.06356417261637282),
 (614, 0.06356417261637282),
 (2419, 0.06356417261637282),
 (3008, 0.06356417261637282),
 (3423, 0.06356417261637282),
 (4125, 0.06356417261637282),
 (52, 0.06253053994807226),
 (295, 0.06253053994807226),
 (312, 0.06253053994807226),
 (332, 0.06253053994807226),
 (369, 0.06253053994807226),
 (885, 0.06253053994807226),
 (1294, 0.06253053994807226),
 (2794, 0.06253053994807226),
 (4259, 0.06253053994807226),
 (752, 0.06154574548966637),
 (900, 0.06154574548966637),
 (1473, 0.06154574548966637),
 (1945, 0.06154574548966637),
 (3507, 0.06154574548966637),
 (3864, 0.06154574548966637),
 (632, 0.060606060606060615),
 (847, 0.060606060606060615),
 (854, 0.060606060606060615),
 (988, 0.060606060606060615),
 (1297, 0.060606060606060615),
 (3340, 0.060606060606060615),
 (168, 0.05970814340265321),
 (754, 0.05970814340265321),
 (2644, 0.05970814340265321),
 (3028, 0.05970814340265321),
 (4079, 0.05970814340265321),
 (4451, 0.05970814340265321),
 (266, 0.05884898863364997),
 (1109, 0.05884898863364997),
 (3102, 0.05884898863364997),
 (3206, 0.05884898863364997),
 (4640, 0.05884898863364997),
 (889, 0.058755799361195606),
 (897, 0.05802588531856595),
 (3022, 0.05802588531856595),
 (4246, 0.05802588531856595),
 (4757, 0.05802588531856595),
 (365, 0.05723638070321425),
 (430, 0.05723638070321425),
 (510, 0.05723638070321425),
 (643, 0.05723638070321425),
 (737, 0.05723638070321425),
 (1560, 0.05723638070321425),
 (1823, 0.05723638070321425),
 (7, 0.05647824947249051),
 (473, 0.05647824947249051),
 (536, 0.05647824947249051),
 (908, 0.05647824947249051),
 (1617, 0.05647824947249051),
 (3783, 0.05647824947249051),
 (4045, 0.05647824947249051),
 (158, 0.055749467333806056),
 (647, 0.055749467333806056),
 (1037, 0.055749467333806056),
 (1175, 0.055749467333806056),
 (1202, 0.055749467333806056),
 (1439, 0.055749467333806056),
 (2003, 0.055749467333806056),
 (3464, 0.055749467333806056),
 (85, 0.05567022142689042),
 (228, 0.055048188256318034),
 (270, 0.055048188256318034),
 (1802, 0.055048188256318034),
 (2241, 0.055048188256318034),
 (2376, 0.055048188256318034),
 (2701, 0.055048188256318034),
 (2999, 0.055048188256318034),
 (3013, 0.055048188256318034),
 (3497, 0.055048188256318034),
 (2021, 0.05437272478270369),
 (3309, 0.05437272478270369),
 (589, 0.05372153093502536),
 (1957, 0.05372153093502536),
 (123, 0.053093187320189895),
 (704, 0.053093187320189895),
 (4063, 0.053093187320189895),
 (1018, 0.052486388108147805),
 (1191, 0.052486388108147805),
 (1531, 0.052486388108147805),
 (1538, 0.052486388108147805),
 (1655, 0.052486388108147805),
 (2529, 0.052486388108147805),
 (2789, 0.052486388108147805),
 (3505, 0.052486388108147805),
 (4332, 0.052486388108147805),
 (4512, 0.052486388108147805),
 (4587, 0.052486388108147805),
 (4654, 0.052486388108147805),
 (43, 0.051899929610768204),
 (456, 0.051899929610768204),
 (2018, 0.051899929610768204),
 (2133, 0.051899929610768204),
 (3225, 0.051899929610768204),
 (3560, 0.051899929610768204),
 (1396, 0.05133270023393454),
 (1418, 0.05133270023393454),
 (1963, 0.05133270023393454),
 (2575, 0.05133270023393454),
 (3740, 0.05133270023393454),
 (169, 0.050783671611902566),
 (790, 0.050783671611902566),
 (812, 0.050783671611902566),
 (2663, 0.050783671611902566),
 (274, 0.05048616658197308),
 (5, 0.05025189076296061),
 (1832, 0.05025189076296061),
 (2388, 0.05025189076296061),
 (2880, 0.05025189076296061),
 (2968, 0.05025189076296061),
 (3069, 0.05025189076296061),
 (3462, 0.05025189076296061),
 (3914, 0.05025189076296061),
 (4555, 0.05025189076296061),
 (4718, 0.05025189076296061),
 (4538, 0.04973647313019938),
 (45, 0.0492365963917331),
 (2740, 0.0492365963917331),
 (170, 0.04875149494180871),
 (199, 0.04875149494180871),
 (363, 0.04875149494180871),
 (89, 0.0484881137876427),
 (156, 0.048280454958526765),
 (208, 0.048280454958526765),
 (222, 0.048280454958526765),
 (808, 0.048280454958526765),
 (2760, 0.048280454958526765),
 (3070, 0.048280454958526765),
 (4044, 0.048280454958526765),
 (4243, 0.048280454958526765),
 (4492, 0.048280454958526765),
 (246, 0.047822809985881044),
 (1019, 0.047822809985881044),
 (2439, 0.047822809985881044),
 (4120, 0.047822809985881044),
 (102, 0.04737793696791343),
 (1282, 0.04737793696791343),
 (3441, 0.04737793696791343),
 (939, 0.04694525268130203),
 (2729, 0.04694525268130203),
 (3486, 0.04694525268130203),
 (172, 0.04652421051992355),
 (325, 0.04652421051992355),
 (624, 0.04652421051992355),
 (653, 0.04652421051992355),
 (861, 0.04652421051992355),
 (1828, 0.04652421051992355),
 (1898, 0.04652421051992355),
 (2250, 0.04652421051992355),
 (2367, 0.04652421051992355),
 (2410, 0.04652421051992355),
 (2659, 0.04652421051992355),
 (2712, 0.04652421051992355),
 (2787, 0.04652421051992355),
 (2882, 0.04652421051992355),
 (3072, 0.04652421051992355),
 (3218, 0.04652421051992355),
 (3430, 0.04652421051992355),
 (4412, 0.04652421051992355),
 (139, 0.04611429759107165),
 (1405, 0.04611429759107165),
 (1897, 0.04611429759107165),
 (4559, 0.04611429759107165),
 (84, 0.04571503208824944),
 (153, 0.04571503208824944),
 (238, 0.04532596090993367),
 (1659, 0.04532596090993367),
 (63, 0.04494665749754947),
 (179, 0.04494665749754947),
 (189, 0.04494665749754947),
 (251, 0.04494665749754947),
 (1130, 0.04494665749754947),
 (1288, 0.04494665749754947),
 (1639, 0.04494665749754947),
 (2259, 0.04494665749754947),
 (2698, 0.04494665749754947),
 (2772, 0.04494665749754947),
 (3753, 0.04494665749754947),
 (4594, 0.04494665749754947),
 (4305, 0.04457671986919932),
 (1120, 0.04421576882853819),
 (2763, 0.04421576882853819),
 (1089, 0.043863446330651264),
 (2150, 0.043863446330651264),
 (490, 0.04351941398892446),
 (1327, 0.04351941398892446),
 (1769, 0.04351941398892446),
 (1782, 0.04351941398892446),
 (1911, 0.04351941398892446),
 (2504, 0.04351941398892446),
 (2634, 0.04351941398892446),
 (2762, 0.04351941398892446),
 (3117, 0.04351941398892446),
 (3253, 0.04351941398892446),
 (3716, 0.04351941398892446),
 (4000, 0.04351941398892446),
 (127, 0.04222003309207491),
 (1301, 0.04222003309207491),
 (1373, 0.04222003309207491),
 (1553, 0.04222003309207491),
 (2457, 0.04222003309207491),
 (3176, 0.04222003309207491),
 (3398, 0.04222003309207491),
 (3671, 0.04222003309207491),
 (3982, 0.04222003309207491),
 (3999, 0.04222003309207491),
 (4018, 0.04222003309207491),
 (4490, 0.04222003309207491),
 (4632, 0.04222003309207491),
 (4638, 0.04222003309207491),
 (81, 0.041612518928823956),
 (160, 0.041612518928823956),
 (488, 0.041612518928823956),
 (418, 0.04103049699311092),
 (505, 0.04103049699311092),
 (570, 0.04103049699311092),
 (2199, 0.04103049699311092),
 (2783, 0.04103049699311092),
 (3297, 0.04103049699311092),
 (3542, 0.04103049699311092),
 (4006, 0.04103049699311092),
 (4351, 0.04103049699311092),
 (4741, 0.04103049699311092),
 (206, 0.04074849710853642),
 (56, 0.03993615319154359),
 (476, 0.03993615319154359),
 (506, 0.03993615319154359),
 (530, 0.03993615319154359),
 (533, 0.03993615319154359),
 (621, 0.03993615319154359),
 (1156, 0.03993615319154359),
 (1171, 0.03993615319154359),
 (1573, 0.03993615319154359),
 (1668, 0.03993615319154359),
 (1833, 0.03993615319154359),
 (1944, 0.03993615319154359),
 (2017, 0.03993615319154359),
 (2112, 0.03993615319154359),
 (2233, 0.03993615319154359),
 (2308, 0.03993615319154359),
 (3515, 0.03993615319154359),
 (3678, 0.03993615319154359),
 (4324, 0.03993615319154359),
 (799, 0.039675980042907705),
 (3201, 0.039675980042907705),
 (887, 0.03942082639927218),
 (1908, 0.03917053290746374),
 (148, 0.03892494720807615),
 (308, 0.03892494720807615),
 (669, 0.03892494720807615),
 (791, 0.03892494720807615),
 (1158, 0.03892494720807615),
 (3502, 0.03892494720807615),
 (3650, 0.03892494720807615),
 (4198, 0.03892494720807615),
 (4331, 0.03892494720807615),
 (4472, 0.03892494720807615),
 (4591, 0.03892494720807615),
 (2386, 0.03821501017343418),
 (25, 0.03798685881987932),
 (105, 0.03798685881987932),
 (157, 0.03798685881987932),
 (348, 0.03798685881987932),
 (878, 0.03798685881987932),
 (1047, 0.03798685881987932),
 (1096, 0.03798685881987932),
 (1303, 0.03798685881987932),
 (1304, 0.03798685881987932),
 (1381, 0.03798685881987932),
 (1881, 0.03798685881987932),
 (2015, 0.03798685881987932),
 (2144, 0.03798685881987932),
 (2948, 0.03798685881987932),
 (3931, 0.03798685881987932),
 (4216, 0.03798685881987932),
 (4623, 0.03798685881987932),
 (3810, 0.037762745602468055),
 (304, 0.03754255278891389),
 (68, 0.037113480951260276),
 (389, 0.037113480951260276),
 (404, 0.037113480951260276),
 (415, 0.037113480951260276),
 (546, 0.037113480951260276),
 (1428, 0.037113480951260276),
 (1586, 0.037113480951260276),
 (1671, 0.037113480951260276),
 (1849, 0.037113480951260276),
 (1973, 0.037113480951260276),
 (2651, 0.037113480951260276),
 (3060, 0.037113480951260276),
 (3306, 0.037113480951260276),
 (3956, 0.037113480951260276),
 (4038, 0.037113480951260276),
 (4312, 0.037113480951260276),
 (4408, 0.037113480951260276),
 (4468, 0.037113480951260276),
 (4482, 0.037113480951260276),
 (4652, 0.037113480951260276),
 (401, 0.03629770043203139),
 (945, 0.03629770043203139),
 (951, 0.03629770043203139),
 (1016, 0.03629770043203139),
 (1027, 0.03629770043203139),
 (1408, 0.03629770043203139),
 (1607, 0.03629770043203139),
 (1686, 0.03629770043203139),
 (2057, 0.03629770043203139),
 (2155, 0.03629770043203139),
 (2378, 0.03629770043203139),
 (2506, 0.03629770043203139),
 (2718, 0.03629770043203139),
 (2990, 0.03629770043203139),
 (3093, 0.03629770043203139),
 (3165, 0.03629770043203139),
 (3373, 0.03629770043203139),
 (3834, 0.03629770043203139),
 (4485, 0.03629770043203139),
 (137, 0.035909478570327065),
 (599, 0.035719981318454656),
 (142, 0.03553345272593508),
 (362, 0.03553345272593508),
 (483, 0.03553345272593508),
 (1249, 0.03553345272593508),
 (1469, 0.03553345272593508),
 (3091, 0.03553345272593508),
 (3135, 0.03553345272593508),
 (3195, 0.03553345272593508),
 (3304, 0.03553345272593508),
 (3316, 0.03553345272593508),
 (3977, 0.03553345272593508),
 (4112, 0.03553345272593508),
 (4292, 0.03553345272593508),
 (4781, 0.03553345272593508),
 (28, 0.03481553119113957),
 (88, 0.03481553119113957),
 (492, 0.03481553119113957),
 (1420, 0.03481553119113957),
 (1523, 0.03481553119113957),
 (1840, 0.03481553119113957),
 (2022, 0.03481553119113957),
 (2159, 0.03481553119113957),
 (2235, 0.03481553119113957),
 (2347, 0.03481553119113957),
 (2589, 0.03481553119113957),
 (2817, 0.03481553119113957),
 (2868, 0.03481553119113957),
 (3354, 0.03481553119113957),
 (3448, 0.03481553119113957),
 (3860, 0.03481553119113957),
 (4085, 0.03481553119113957),
 (4618, 0.03481553119113957),
 (4661, 0.03481553119113957),
 (4673, 0.03481553119113957),
 (49, 0.03413943709994595),
 (244, 0.03413943709994595),
 (294, 0.03413943709994595),
 (306, 0.03413943709994595),
 (356, 0.03413943709994595),
 (794, 0.03413943709994595),
 (823, 0.03413943709994595),
 (844, 0.03413943709994595),
 (1070, 0.03413943709994595),
 (1440, 0.03413943709994595),
 (1443, 0.03413943709994595),
 (1556, 0.03413943709994595),
 (1982, 0.03413943709994595),
 (2138, 0.03413943709994595),
 (2169, 0.03413943709994595),
 (3785, 0.03413943709994595),
 (3816, 0.03413943709994595),
 (4575, 0.03413943709994595),
 (125, 0.03365744438798206),
 (21, 0.033501260508640406),
 (86, 0.033501260508640406),
 (439, 0.033501260508640406),
 (1141, 0.033501260508640406),
 (1391, 0.033501260508640406),
 (1928, 0.033501260508640406),
 (2304, 0.033501260508640406),
 (2689, 0.033501260508640406),
 (2726, 0.033501260508640406),
 (2824, 0.033501260508640406),
 (4626, 0.033501260508640406),
 (166, 0.03289758474798845),
 (227, 0.03289758474798845),
 (245, 0.03289758474798845),
 (512, 0.03289758474798845),
 (894, 0.03289758474798845),
 (899, 0.03289758474798845),
 (937, 0.03289758474798845),
 (1768, 0.03289758474798845),
 (1816, 0.03289758474798845),
 (2535, 0.03289758474798845),
 (3074, 0.03289758474798845),
 (3131, 0.03289758474798845),
 (3164, 0.03289758474798845),
 (3647, 0.03289758474798845),
 (4114, 0.03289758474798845),
 (4327, 0.03289758474798845),
 (4720, 0.03289758474798845),
 (2995, 0.03246565023717827),
 (75, 0.0323254091917618),
 (837, 0.0323254091917618),
 (855, 0.0323254091917618),
 (1312, 0.0323254091917618),
 (2066, 0.0323254091917618),
 (2230, 0.0323254091917618),
 (2892, 0.0323254091917618),
 (3679, 0.0323254091917618),
 (4037, 0.0323254091917618),
 (4773, 0.0323254091917618),
 (3368, 0.03191534511615646),
 (254, 0.03178208630818641),
 (282, 0.03178208630818641),
 (413, 0.03178208630818641),
 (617, 0.03178208630818641),
 (1199, 0.03178208630818641),
 (1243, 0.03178208630818641),
 (2449, 0.03178208630818641),
 (2478, 0.03178208630818641),
 (2632, 0.03178208630818641),
 (2879, 0.03178208630818641),
 (2943, 0.03178208630818641),
 (2964, 0.03178208630818641),
 (3140, 0.03178208630818641),
 (3235, 0.03178208630818641),
 (3329, 0.03178208630818641),
 (4377, 0.03178208630818641),
 (4657, 0.03178208630818641),
 (126, 0.03126526997403613),
 (257, 0.03126526997403613),
 (395, 0.03126526997403613),
 (871, 0.03126526997403613),
 (883, 0.03126526997403613),
 (1399, 0.03126526997403613),
 (2013, 0.03126526997403613),
 (2224, 0.03126526997403613),
 (2450, 0.03126526997403613),
 (2502, 0.03126526997403613),
 (3011, 0.03126526997403613),
 (3349, 0.03126526997403613),
 (3389, 0.03126526997403613),
 (3664, 0.03126526997403613),
 (4209, 0.03126526997403613),
 (4510, 0.03126526997403613),
 (4799, 0.03126526997403613),
 (57, 0.030772872744833184),
 (60, 0.030772872744833184),
 (131, 0.030772872744833184),
 (521, 0.030772872744833184),
 (535, 0.030772872744833184),
 (588, 0.030772872744833184),
 (634, 0.030772872744833184),
 (646, 0.030772872744833184),
 (672, 0.030772872744833184),
 (807, 0.030772872744833184),
 (875, 0.030772872744833184),
 (1247, 0.030772872744833184),
 (1612, 0.030772872744833184),
 (1646, 0.030772872744833184),
 (2253, 0.030772872744833184),
 (2605, 0.030772872744833184),
 (3100, 0.030772872744833184),
 (3233, 0.030772872744833184),
 (3620, 0.030772872744833184),
 (3673, 0.030772872744833184),
 (3735, 0.030772872744833184),
 (4675, 0.030772872744833184),
 (37, 0.030303030303030307),

In [55]:
sorted(list(enumerate(similarity[0])), reverse=True, key= lambda x:x[1]) [1:6]

[(3608, 0.21320071635561044),
 (1216, 0.20769510081357428),
 (1920, 0.2059714602177749),
 (582, 0.20533080093573816),
 (539, 0.20100756305184245)]

In [56]:
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    for i in movies_list:
        print(i[0])

In [57]:
recommend('Avatar')

3608
1216
1920
582
539

In [58]:
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [59]:
recommend('Avatar') # Every movie based on the Alien

Apollo 18
Aliens vs Predator: Requiem
Lifeforce
Battle: Los Angeles
Titan A.E.

In [61]:
import pickle

In [62]:
pickle.dump(new_df, open('movies.pkl','wb'))

In [64]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [65]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [66]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))